version: '3.4'

services:
  companydb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  stockdb:
    image: mongo

  companyapi-service:
    image: ${DOCKER_REGISTRY-}companysapi
    build:
      context: .
      dockerfile: Microservices/Companys/Companys.API/Dockerfile

  stockapi-service:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Microservices/Stocks/Stock.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

  ocelotgw.api:
    image: ${DOCKER_REGISTRY-}ocelotgwapi
    build:
      context: .
      dockerfile: Gateway/OcelotGw.API/Dockerfile

  aggregatorapi-service:
    image: ${DOCKER_REGISTRY-}aggregatorapi
    build:
      context: .
      dockerfile: Gateway/Aggregator.API/Dockerfile

  healthchkapi-service:
    image: ${DOCKER_REGISTRY-}healthcheck
    build:
      context: .
      dockerfile: Monitor/HealthCheck/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  #estockmarket:
  #  image: ${DOCKER_REGISTRY-}estockmarket
  #  build:
  #    context: .
  #    dockerfile: Monitor/eStockMarket/Dockerfile

volumes:
  sql_data:
  mongo_data:
  elasticsearch-data:
